parameters:
  blog_parse_url: "https://shkolazhizni.ru/articles/"

services:

   BlogBundle\BlogBundle\Command\:
      resource: '../../Command'
      tags: [console.command]

   blog.bundle.parser:
      class: BlogBundle\BlogBundle\Service\ParserService
      arguments:
      [
          '@service_container',
          '@doctrine.orm.entity_manager'
      ]
      tags:
      - { name: blog_bundle.parser }
